# Types of api calls you can use
rapidpro_api_settings:
    - request_types:
        - getcontacts: "https://api.rapidpro.io/api/v2/contacts.json"
        - getruns: "https://api.rapidpro.io/api/v2/runs.json"
        - getmessages: "http://example.com/api/v2/messages.json"

# Data export settings
data_export_settings:
    - export_to_file: 
        - export: true
        - path: "data/processed"
        - fileType: "csv"       # The file type can be csv or json
    # You can set up the DB connexion credentials in the .env file
    - export_to_database: true

# fieldgroup
covid_education_poll_columns:
    - id
    - exit_type
    - contact:
        - uuid
        - name
    - values:
        - is_going_to_school:
            - value
        - is_learning_online:
            - value

# fieldgroup
health_agents:
    - uuid
    - name
    - blocked
    - created_on
    - modified_on
    - fields:
        - field1
        - field2
        - field3