# Types of api requests you can use
# You can customize the requests by adding parameters that comply with the RapidPro API
rapidpro_api_settings:
    - request_types:
        - getcontacts: "https://api.rapidpro.io/api/v2/contacts.json"
        - getruns: "https://api.rapidpro.io/api/v2/runs.json"
        - getmessages: "https://api.rapidpro.io/api/v2/messages.json"
        - getcampaigns: "https://api.rapidpro.io/api/v2/campaigns.json"
        - getarchives: "https://api.rapidpro.io/api/v2/archives.json"


# Data export settings
data_export_settings:
    - export_to_file: 
        - export: true
        - path: "data/processed"
        - fileType: "csv"       # The file type can be csv or json

    # Set up the DB connexion credentials in the .env file
    - export_to_database: true


# The field groups define the data fields you want to export from the API response.

# fieldgroup
covid_edu_poll:
    - id
    - exit_type
    - contact:
        - uuid
        - name
    - values:
        - is_going_to_school:
            - value
        - is_learning_online:
            - value

# fieldgroup
health_agents:
    - uuid
    - name
    - blocked
    - created_on
    - modified_on
    - fields:
        - field1
        - field2
        - field3